[build]
  bin = "/bin/sleep 0"
  cmd = "make ready day=$( find ./2023 -d -maxdepth 1 -mindepth 1 | sort | tail -1 )"
  delay = 500 # ms
  exclude_unchanged = true
  log = "/tmp/air.log"
  stop_on_error = false
